parameters:
    databaseDir: '%rootDir%/wordnet-db/'

services:
    _defaults:
        autowire: true
        bind:
            PhpWndb\Dataset\Storage\Storage: '@PhpWndb\Dataset\Storage\FileStorage'
            PhpWndb\Dataset\Storage\StreamSearcher: '@PhpWndb\Dataset\Storage\StreamBinarySearcher'

    search:
        namespace: 'PhpWndb\Dataset\'
        resource: '../src/**/*{Factory,Mapper,Parser,Repository,SearchEngine}.php'


    PhpWndb\Dataset\Storage\FileStorage:
        arguments:
            $filesDir: '%databaseDir%'

    PhpWndb\Dataset\Repository\Index\IndexRepository:
        arguments:
            $sourceSyntacticCategories:
                - !php/enum PhpWndb\Dataset\Model\Index\SyntacticCategory::NOUN
                - !php/enum PhpWndb\Dataset\Model\Index\SyntacticCategory::VERB
                - !php/enum PhpWndb\Dataset\Model\Index\SyntacticCategory::ADJECTIVE
                - !php/enum PhpWndb\Dataset\Model\Index\SyntacticCategory::ADVERB

    PhpWndb\Dataset\Storage\StreamBinarySearcher: ~

    PhpWndb\Dataset\WordNet:
        public: true
